import localFont from "next/font/local";
import { Box } from '@mui/material';
import "./globals.css";

import ThemeProvider from './ThemeProvider';
import UserDataProvider from './UserDataProvider';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box width="100vw" height="100vh">
          <ThemeProvider>
            <UserDataProvider>
              {children}
            </UserDataProvider>
          </ThemeProvider>
        </Box>
      </body>
    </html>
  );
}
